Readme and linters
eroiyo/Conference-Web pull request #1
Opened 2021-07-01 19:43 UTC by eroiyo

HTML/CSS & JavaScript capstone project
Project requirements
Personalize the content of the page. Choose a topic first and then design the webpage.
Build only these 2 pages:
The home page.
The about page.
Each of these pages should have versions for 2 different screens sizes:
Mobile: up to 768px wide.
Desktop: 768px or wider.
Follow the design guidelines, including:
Colors.
Typography: font face, size, and weight.
Layout: composition and space between elements.
Interactions
Links
The home page should have a link in the menu to the about page.
The logo in the header links to the home page.
Mobile menu
When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
There are no guidelines for the mobile menu in the docs but implement it so it is consistent with the design (colors, typography, spacings, etc.).
The mobile menu should have a close (X) button that closes the menu.
Dynamic page
The section "Featured speakers" should be created dynamically in JavaScript.
Use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.

2021-07-01 22:01 UTC, eroiyo commented
Hello, i am ready for the first code review!  🔥

2021-07-02 00:20 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 5 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-02 00:20 UTC, vichuge commented on about.html
> +        </footer>
- [ ] It would be better if the `<footer>` section has a white background for mobile size and a dark background for desktop. 🐔 
![image](https://user-images.githubusercontent.com/20563252/124202174-76a34980-da9f-11eb-966c-34b68150e3db.png)

2021-07-02 00:20 UTC, vichuge commented on about.html
> +    </header>
- [ ] Please, the navbar should be divided into a top dark bar and a bottom white bar. The white design is good, just add the black navbar at the top. 🌵 

| original | yours |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20563252/124201936-ec5ae580-da9e-11eb-8cb5-f7c93138df8d.png) | ![image](https://user-images.githubusercontent.com/20563252/124202016-1f04de00-da9f-11eb-8af3-e8cc47f98414.png) |

2021-07-02 00:20 UTC, vichuge commented on about.html
> +    </header>
- [ ] The navbar for mobile size should have a background because sometimes the burger Icon with other elements is confusing. I kindly invite you to fix it. 🐤 
![image](https://user-images.githubusercontent.com/20563252/124202456-ff21ea00-da9f-11eb-9a17-66f14d47ffb6.png)

2021-07-02 08:37 UTC, eroiyo commented
Thanks for the suggestions, I will be working in these!

2021-07-02 10:15 UTC, eroiyo commented
* Added the login bar
* The footer change colors depending of the screensizes
* change the partner section color to contrast in any case

2021-07-02 11:11 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @eroiyo     ! :wave: :wave:

#### You have done really well in implementing the previously required changes.
 However, there are changes required for you to make in order for this project to be approved. 

- - -

### **Required Changes** ♻️
- [ ] Kindly note, that you have to follow the given design template. 
_See the inline comments below for more required changes_

### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**
__Kindly make the necessary changes and submit another code review request.__

2021-07-02 11:11 UTC, Temmarie commented on about.html
> +        </footer>
- [ ] The footer for the about page should be a dark grey on desktop screens, and then have both sections on mobile screens.

_See images below._

**Original** | **Your project**
  ----------- | -----------
  | Desktop screens | 
  ![image](https://user-images.githubusercontent.com/49621279/124263264-e2110980-dae7-11eb-9599-0bc3a6900080.png) | ![image](https://user-images.githubusercontent.com/49621279/124263400-0d93f400-dae8-11eb-8845-6dd516f34be9.png)
 | Mobile screens | 
![image](https://user-images.githubusercontent.com/49621279/124265157-31f0d000-daea-11eb-8c3b-586a303d177b.png) | ![image](https://user-images.githubusercontent.com/49621279/124265279-5482e900-daea-11eb-80a1-01c454d62d33.png)

2021-07-02 12:26 UTC, eroiyo commented
Thanks, i will be working on it!

2021-07-02 13:35 UTC, Dipeshtwis requested changes
Hi @eroiyo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-02 13:35 UTC, Dipeshtwis commented on exclusive-footer.css
> +}
- [ ] This is interchanged. Because of this your footer has opposite color what was required from the original both in about and html. 

### Your design 

![Screenshot from 2021-07-02 18-55-39](https://user-images.githubusercontent.com/22434660/124281944-df55f900-db67-11eb-9b03-06a7b688fa41.png)


### Original design

![Screenshot from 2021-07-02 18-55-22](https://user-images.githubusercontent.com/22434660/124281964-e3821680-db67-11eb-9f33-3a4a5a6a0707.png)

2021-07-02 13:47 UTC, eroiyo commented on exclusive-footer.css
> +}
Thanks. 😃

2021-07-02 15:27 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @eroiyo, 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-02 15:48 UTC, merged